hybrid:
strategy_weights:
default: {'A': 0.5, 'hybrid': 0.3, 'B': 0.2}
bull_strong: {'A': 0.6, 'hybrid': 0.3, 'B': 0.1}
bear_strong: {'A': 0.3, 'hybrid': 0.4, 'B': 0.3}

asset_universe:
primary: ['BTC-USD', 'ETH-USD', 'SOL-USD']
secondary: ['ADA-USD', 'AVAX-USD', 'MATIC-USD']
tertiary: ['ATOM-USD', 'DOT-USD', 'LINK-USD']

position_sizing:
A:
base: 0.02
max: 0.05
hybrid:
base: 0.015
max: 0.03
B:
base: 0.008
max: 0.015

profit_enhancements:
volatility_entry: true
sentiment_scaling: true
liquidity_exit: true
dynamic_targeting: true
time_scaling: true
win_optimization: true
